# Generated by Django 5.0 on 2023-12-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_doctorregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistration',
            name='doctor_speciality',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
    ]
